# Generated by Django 6.0 on 2025-12-22 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carreta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('marca', models.CharField(blank=True, max_length=100, null=True)),
                ('modelo', models.CharField(blank=True, max_length=100, null=True)),
                ('ano', models.IntegerField(blank=True, null=True)),
                ('cor', models.CharField(blank=True, max_length=50, null=True)),
                ('ultima_lavagem', models.DateField(blank=True, null=True, verbose_name='Última Lavagem')),
                ('proxima_lavagem', models.DateField(blank=True, null=True, verbose_name='Próxima Lavagem')),
                ('polietileno', models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'Não'), ('metade', 'Metade'), ('danificado', 'Danificado')], max_length=20, null=True)),
                ('cones', models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'Não')], max_length=10, null=True)),
                ('localizador', models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'Não'), ('nao_funciona', 'Não Funciona')], max_length=20, null=True)),
                ('lona_facil', models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'Não')], max_length=10, null=True)),
                ('step', models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'Não')], max_length=10, null=True)),
                ('tipo', models.CharField(blank=True, choices=[('ls_curta', 'LS Curta'), ('canguru', 'Canguru'), ('vanderleia', 'Vanderleia')], max_length=20, null=True)),
                ('altura', models.CharField(blank=True, choices=[('baixa', 'Baixa'), ('alta', 'Alta')], max_length=10, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Carreta',
                'verbose_name_plural': 'Carretas',
                'ordering': ['placa'],
            },
        ),
        migrations.CreateModel(
            name='Gestor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=255, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Gestor',
                'verbose_name_plural': 'Gestores',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Proprietario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_razao_social', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo', models.CharField(blank=True, choices=[('PF', 'Pessoa Física'), ('PJ', 'Pessoa Jurídica')], max_length=2, null=True)),
                ('documento', models.FileField(blank=True, null=True, upload_to='proprietarios/documentos/')),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Proprietário',
                'verbose_name_plural': 'Proprietários',
                'ordering': ['nome_razao_social'],
            },
        ),
        migrations.CreateModel(
            name='Cavalo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('ano', models.IntegerField(blank=True, null=True)),
                ('cor', models.CharField(blank=True, max_length=50, null=True)),
                ('fluxo', models.CharField(blank=True, choices=[('escoria', 'Escória'), ('minerio', 'Minério')], max_length=20, null=True)),
                ('situacao', models.CharField(blank=True, choices=[('ativo', 'Ativo'), ('quebrado', 'Quebrado'), ('desagregado', 'Desagregado')], max_length=20, null=True)),
                ('documento', models.FileField(blank=True, null=True, upload_to='cavalos/documentos/')),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('carreta', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cavalo_acoplado', to='core.carreta', verbose_name='Carreta Agregada')),
                ('gestor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cavalos', to='core.gestor', verbose_name='Gestor')),
                ('proprietario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cavalos', to='core.proprietario', verbose_name='Proprietário')),
            ],
            options={
                'verbose_name': 'Cavalo',
                'verbose_name_plural': 'Cavalos',
                'ordering': ['placa'],
            },
        ),
        migrations.CreateModel(
            name='LogCarreta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('acoplamento', 'Acoplamento'), ('desacoplamento', 'Desacoplamento'), ('troca', 'Troca de Carreta'), ('desagregacao', 'Desagregação')], max_length=20)),
                ('carreta_anterior', models.CharField(blank=True, max_length=10, null=True, verbose_name='Placa Carreta Anterior')),
                ('carreta_nova', models.CharField(blank=True, max_length=10, null=True, verbose_name='Placa Carreta Nova')),
                ('placa_cavalo', models.CharField(blank=True, max_length=10, null=True, verbose_name='Placa do Cavalo')),
                ('descricao', models.TextField(blank=True, null=True)),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('cavalo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='core.cavalo', verbose_name='Cavalo')),
            ],
            options={
                'verbose_name': 'Log de Carreta',
                'verbose_name_plural': 'Logs de Carretas',
                'ordering': ['-data_hora'],
            },
        ),
        migrations.CreateModel(
            name='Motorista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=255, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cavalo', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='motorista', to='core.cavalo', verbose_name='Cavalo')),
            ],
            options={
                'verbose_name': 'Motorista',
                'verbose_name_plural': 'Motoristas',
                'ordering': ['nome'],
            },
        ),
    ]
