# Generated by Django 6.0 on 2025-12-30 16:21

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarcaCarreta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Marca')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
            ],
            options={
                'verbose_name': 'Marca de Carreta',
                'verbose_name_plural': 'Marcas de Carreta',
                'db_table': 'marcas_carreta',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='MarcaCavalo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Marca')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
            ],
            options={
                'verbose_name': 'Marca de Cavalo',
                'verbose_name_plural': 'Marcas de Cavalo',
                'db_table': 'marcas_cavalo',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='UploadLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo_nome', models.CharField(max_length=500, verbose_name='Nome do Arquivo')),
                ('tipo_detectado', models.CharField(blank=True, max_length=10, null=True, verbose_name='Tipo Detectado')),
                ('status', models.CharField(choices=[('PROCESSANDO', 'Processando'), ('SUCESSO', 'Sucesso'), ('ERRO', 'Erro')], default='PROCESSANDO', max_length=20, verbose_name='Status')),
                ('registros_processados', models.IntegerField(default=0, verbose_name='Registros Processados')),
                ('registros_duplicados', models.IntegerField(default=0, verbose_name='Registros Duplicados')),
                ('mensagem_erro', models.TextField(blank=True, null=True, verbose_name='Mensagem de Erro')),
                ('data_upload', models.DateTimeField(auto_now_add=True, verbose_name='Data do Upload')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Log de Upload',
                'verbose_name_plural': 'Logs de Upload',
                'ordering': ['-data_upload'],
            },
        ),
        migrations.CreateModel(
            name='DocumentoTransporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('CTE', 'CTE'), ('OST', 'OST')], max_length=3, verbose_name='Tipo de Documento')),
                ('filial', models.CharField(blank=True, max_length=50, null=True, verbose_name='Filial')),
                ('serie', models.CharField(blank=True, max_length=50, null=True, verbose_name='Série')),
                ('numero_documento', models.CharField(blank=True, max_length=50, null=True, verbose_name='Número do Documento')),
                ('data_documento', models.DateField(blank=True, null=True, verbose_name='Data do Documento')),
                ('motorista', models.CharField(blank=True, max_length=200, null=True, verbose_name='Motorista')),
                ('cavalo', models.CharField(blank=True, max_length=10, null=True, verbose_name='Placa do Cavalo')),
                ('carreta', models.CharField(blank=True, max_length=10, null=True, verbose_name='Placa da Carreta')),
                ('tipo_frota', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo de Frota')),
                ('remetente', models.CharField(blank=True, max_length=500, null=True, verbose_name='Remetente')),
                ('destinatario', models.CharField(blank=True, max_length=500, null=True, verbose_name='Destinatário')),
                ('nota_fiscal', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nota Fiscal')),
                ('pedagio', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Pedágio')),
                ('total_frete', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Total do Frete')),
                ('tarifa', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Tarifa')),
                ('filial_serie_numero', models.CharField(blank=True, max_length=200, null=True, verbose_name='Filial/Série/Número')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('gestor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos', to='core.gestor', verbose_name='Gestor')),
            ],
            options={
                'verbose_name': 'Documento de Transporte',
                'verbose_name_plural': 'Documentos de Transporte',
                'ordering': ['-data_documento', '-created_at'],
                'indexes': [models.Index(fields=['tipo_documento', 'filial', 'serie', 'numero_documento'], name='core_docume_tipo_do_f5834f_idx'), models.Index(fields=['data_documento'], name='core_docume_data_do_9bab10_idx'), models.Index(fields=['motorista'], name='core_docume_motoris_2fe774_idx'), models.Index(fields=['cavalo'], name='core_docume_cavalo_47dee2_idx'), models.Index(fields=['gestor'], name='core_docume_gestor__7fccf1_idx')],
            },
        ),
        migrations.CreateModel(
            name='ModeloCarreta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Modelo')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modelos', to='core.marcacarreta', verbose_name='Marca')),
            ],
            options={
                'verbose_name': 'Modelo de Carreta',
                'verbose_name_plural': 'Modelos de Carreta',
                'db_table': 'modelos_carreta',
                'ordering': ['marca__nome', 'nome'],
                'unique_together': {('marca', 'nome')},
            },
        ),
        migrations.CreateModel(
            name='ModeloCavalo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Modelo')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modelos', to='core.marcacavalo', verbose_name='Marca')),
            ],
            options={
                'verbose_name': 'Modelo de Cavalo',
                'verbose_name_plural': 'Modelos de Cavalo',
                'db_table': 'modelos_cavalo',
                'ordering': ['marca__nome', 'nome'],
                'unique_together': {('marca', 'nome')},
            },
        ),
    ]
