# Generated by Django 6.0 on 2025-12-30 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_marcacarreta_marcacavalo_uploadlog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proprietario',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
    ]
