# Generated by Django 6.0 on 2025-12-30 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_proprietario_ativo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proprietario',
            name='ativo',
        ),
        migrations.AddField(
            model_name='proprietario',
            name='status',
            field=models.CharField(choices=[('sim', 'Sim'), ('nao', 'Não')], default='sim', max_length=3, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='proprietario',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='WhatsApp'),
        ),
    ]
