# Generated by Django 6.0 on 2025-12-30 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_proprietario_ativo_proprietario_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carreta',
            name='altura',
        ),
        migrations.AddField(
            model_name='carreta',
            name='documento',
            field=models.FileField(blank=True, null=True, upload_to='carretas/documentos/', verbose_name='Documento'),
        ),
        migrations.AddField(
            model_name='carreta',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='carretas/fotos/', verbose_name='Foto'),
        ),
        migrations.AddField(
            model_name='carreta',
            name='local',
            field=models.CharField(blank=True, help_text='Atualizado automaticamente por API', max_length=255, null=True, verbose_name='Local'),
        ),
        migrations.AlterField(
            model_name='carreta',
            name='tipo',
            field=models.CharField(blank=True, choices=[('baixa', 'Baixa'), ('alta', 'Alta'), ('canguru', 'Canguru'), ('vanderleia', 'Vanderleia')], max_length=20, null=True),
        ),
    ]
