# Generated by Django 6.0 on 2025-12-31 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_carreta_altura_carreta_documento_carreta_foto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cavalo',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='cavalos/fotos/', verbose_name='Foto'),
        ),
        migrations.AddField(
            model_name='cavalo',
            name='tipo',
            field=models.CharField(blank=True, choices=[('toco', 'Toco'), ('trucado', 'Trucado')], max_length=20, null=True, verbose_name='Tipo'),
        ),
        migrations.AddField(
            model_name='motorista',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='CPF'),
        ),
        migrations.AddField(
            model_name='motorista',
            name='documento',
            field=models.FileField(blank=True, null=True, upload_to='motoristas/documentos/', verbose_name='Documento'),
        ),
        migrations.AddField(
            model_name='motorista',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='motoristas/fotos/', verbose_name='Foto'),
        ),
        migrations.AddField(
            model_name='motorista',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='WhatsApp'),
        ),
    ]
