# Generated by Django 6.0 on 2025-12-31 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_cavalo_foto_cavalo_tipo_motorista_cpf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='logcarreta',
            name='motorista_anterior',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Motorista Anterior'),
        ),
        migrations.AddField(
            model_name='logcarreta',
            name='motorista_novo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Motorista Novo'),
        ),
        migrations.AddField(
            model_name='logcarreta',
            name='proprietario_anterior',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Proprietário Anterior'),
        ),
        migrations.AddField(
            model_name='logcarreta',
            name='proprietario_novo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Proprietário Novo'),
        ),
        migrations.AlterField(
            model_name='logcarreta',
            name='tipo',
            field=models.CharField(choices=[('acoplamento', 'Acoplamento'), ('desacoplamento', 'Desacoplamento'), ('troca', 'Troca de Carreta'), ('desagregacao', 'Desagregação'), ('motorista_adicionado', 'Motorista Adicionado'), ('motorista_removido', 'Motorista Removido'), ('motorista_alterado', 'Motorista Alterado'), ('proprietario_alterado', 'Proprietário Alterado')], max_length=25),
        ),
    ]
