# Generated by Django 6.0 on 2025-12-31 04:36

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_logcarreta_motorista_anterior_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gestor',
            name='meta_faturamento',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Meta de Faturamento'),
        ),
        migrations.CreateModel(
            name='HistoricoGestor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField(verbose_name='Data de Início')),
                ('data_fim', models.DateField(blank=True, null=True, verbose_name='Data de Fim')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('cavalo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_gestores', to='core.cavalo', verbose_name='Cavalo')),
                ('gestor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='core.gestor', verbose_name='Gestor')),
            ],
            options={
                'verbose_name': 'Histórico de Gestor',
                'verbose_name_plural': 'Históricos de Gestores',
                'ordering': ['-data_inicio'],
                'indexes': [models.Index(fields=['gestor', 'data_inicio', 'data_fim'], name='core_histor_gestor__d1b003_idx'), models.Index(fields=['cavalo', 'data_inicio', 'data_fim'], name='core_histor_cavalo__be15f4_idx')],
            },
        ),
    ]
