# Generated by Django 6.0 on 2025-12-31 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_gestor_meta_faturamento_historicogestor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logcarreta',
            name='tipo',
            field=models.CharField(choices=[('acoplamento', 'Acoplamento'), ('desacoplamento', 'Desacoplamento'), ('troca', 'Troca de Carreta'), ('desagregacao', 'Desagregação'), ('motorista_adicionado', 'Motorista Adicionado'), ('motorista_removido', 'Motorista Removido'), ('motorista_alterado', 'Motorista Alterado'), ('proprietario_alterado', 'Proprietário Alterado'), ('troca_proprietario', 'Troca de Proprietário')], max_length=25),
        ),
    ]
