# Generated by Django 6.0 on 2025-12-31 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_logcarreta_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='proprietario',
            name='codigo',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Código'),
        ),
    ]
